aai-institute/lakefs-spec

- .github/workflows/python.yaml
- .github/workflows/release.yaml
> feat(ci): Add Python venv cache

- src/lakefs_spec/spec.py
Otherwise, the backend throws a 400 Bad Request. Contrary to the branch creation logic, explicitly request the diff before committing.
Fixes #22.
> Abort commit attempt in postcommit if no changes are present

- .pre-commit-config.yaml
Some extra config was present for files that do not exist anymore, so remove it.
> Remove stale pre-commit configurations, bump ruff to latest v0.0.286

- .github/workflows/python.yaml
- dev-deps.lock
- pyproject.toml
This PR adds coverage recording and upload to [codecov](https://app.codecov.io/gh/appliedAI-Initiative/lakefs-spec) to the CI workflow.
> Record code coverage in CI, upload to Codecov

- README.md
As in title. 
Added an explanation of the implicit branch creation and uploading files in general to the `readme.md`
> Add implicit branch creation and other small changes to Readme.md

- src/lakefs_spec/spec.py
This is useful e.g. for the `pandas` integration. Just as in the file system's `put`, we create a commit directly after upload.
Also consolidates the commit logic into a new method `LakeFSFileSystem.commit()`.
> Add postcommit support for lakeFS files

- src/lakefs_spec/errors.py
This way, we actually display the root cause of the error from the backend and not the minorly useful HTTP error.
> Load and use error message instead of only HTTP reason

- src/lakefs_spec/spec.py
So far, its arguments are unused since we translate the lakeFS errors raw and without custom messages.
Exchanges the verbose try-excepts for an indent level due to the new context manager.
> Add API call wrapper context manager

- .pre-commit-config.yaml
- requirements-dev.txt
- requirements.txt
Contains the results of `pre-commit autoupdate` and `pip-compile ... --upgrade` in two separate commits.
> Update developer tooling

- README.md
Artifact in `Readme.md` from updated functionality is adapted to current functionality
> Remove link deleted section in README.md

- src/lakefs_spec/spec.py
The buffering issue is understood (and also maybe unnecessary) after the first warning, so gate it behind a global and make it once-per-session.
> Only warn once before uploading a raw file

- .github/workflows/python.yaml
- .pre-commit-config.yaml
- hack/docker-compose.yml
Also fix a stale file name in the pre-commit cache key calculation.
> Update lakeFS image in local tests and CI, bump ruff

- .pre-commit-config.yaml
Tests the internal Jira to GitHub integration.
> [ENG-96] Run pre-commit autoupdate

- README.md
Added a pseudo-code example on how to create reproducible code to the `Readme.md`.
Also added a reference to the demo notebook in the introduction at the top of the readme.
> Add Reproducibility Example to Readme.md

- src/lakefs_spec/spec.py
Closes https://github.com/appliedAI-Initiative/lakefs-spec/issues/92
Execute the registered hooks for `FSEvent.PUT_FILE` and `FS_Event.GET_FILE` even if `precheck=True` skips file operations due to no changes.
> Run hooks even if precheck skips fs action [ENG-100]

- src/lakefs_spec/spec.py
- tests/test_lakefs_file.py
Move ensure_branch out of _warn_on_fileupload guard such that it's independent on the warning.
> Move ensure_branch out of _warn_on_[...] check

- src/lakefs_spec/spec.py
Otherwise, if the `objects_api.head_object()` call fails, the context manager jumps to the `finally` block, where `exists` (the boolean) is unbound.
> Fix unbound local error by moving up definition of `exists` boolean

- src/lakefs_spec/spec.py
That part of the implementation was left over from a time when the `LakeFSFile` and `fs.open()` were not implemented. As they are now available, we can defer to the superclass for "normal" file gets.
> Defer to super class for `get_file`

- demos/demo_data_science_project.ipynb
- demos/requirements.txt
The urllib bump is due to a security advisory on GitHub, the lakefs-spec bump is necessary to grab the transaction changes.
The transactions make the notebook flow easier to read, and enable flexible commit messages for each upload of the weather data.
> Update demo to use transactions, bump lakefs-spec to HEAD and urllib

- .gitkeep
- .pre-commit-config.yaml
Bumps `mypy -> v1.7.0`, and `ruff -> v0.1.5`.
> Run `pre-commit autoupdate`, delete unnecessary gitkeep file

- .pre-commit-config.yaml
- pyproject.toml
- src/lakefs_spec/spec.py
See commit messages (or the diff) for further details.
> Delete stale black config and comments, fix error handling in blockstore puts 

- docs/_styles/extra.css
- docs/_styles/theme.css
- mkdocs.yml
This PR includes some small branding improvements to the documentation:
- Proper copyright notice and link
- Dark color scheme, accent colors from brand guide
> Docs: Branding fixes

- pyproject.toml
- src/lakefs_spec/spec.py
- src/lakefs_spec/util.py
Closes https://github.com/aai-institute/lakefs-spec/issues/127
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aai-institute/lakefs-spec/182)
> Allow Path like inputs in public LakeFSFileSystem methods

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
Remove BUG and FTR prefixes from issue templates.
> Remove bug ftr prefix issue templates

- README.md
- docs/index.md
We have used a different list of highlights in our posts/blogs. This PR updates the highlights in the README and the documentation to match those.
Issue: #216
> Docs: Update project highlights

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
As per the title ^^
Feel free to squash commits on merge :)
> Slim down the bug report and feature request templates

- .github/workflows/python.yaml
- .github/workflows/release.yaml
- hack/docker-compose.yml
- hack/lakefs-s3-local.yml
In GitHub CI and local deployments located in the `hack/` folder.
> Bump lakeFS service container version to v1.7.0

- src/lakefs_spec/spec.py
Similar to s3fs, `fs.exists()` should return True also for common prefixes.
Ran into this while trying to use lakefs-spec with [HuggingFace Datasets](https://huggingface.co/docs/datasets/en/index) - loading a dataset accepts a directory uri, which is checked for existence and subsequently fails.
The check is done in a similar fashion to [s3fs'](https://github.com/fsspec/s3fs/blob/main/s3fs/core.py#L1397) - ensure path ends with `'/'`, attempt listing, return True if there's anything under that prefix.
> fs.exists() should return True for common prefixes
