- src/lakefs_spec/spec.py
- tests/test_lakefs_file.py
Since the lakeFS client does not allow multipart uploads, as a workaround, write the whole file in a single chunk. Warn about the performance indications as well.
TODO:
> Implement `LakeFSFileSystem.open()` in write mode

- .github/workflows/python.yaml
- dev-deps.lock
- pyproject.toml
- tests/conftest.py
https://github.com/treeverse/lakeFS/issues/6452 revealed that there is a possibility to emulate the quickstart via some environment variables.
This commit sets them and defines a GitHub Actions service container from the latest lakeFS tag to try and see if that works.
> Switch lakeFS CI instance to service container

- src/lakefs_spec/spec.py
- tests/test_put_file.py
That was missing from the previous commithook fix.
> Add a test for an empty diff in postcommit

- CONTRIBUTING.md
- README.md
- pyproject.toml
- src/lakefs_spec/__init__.py
- tests/test_checksum.py
- tests/test_get_file.py
- tests/test_lakefs_file.py
- tests/test_ls.py
- tests/test_put_file.py
Adjust all example imports in the README and the registration hooks for `pyproject.toml`.
> Move lakeFS file system and file to top-level module

- hack/docker-compose.yml
- tests/conftest.py
- tests/test_checksum.py
- tests/test_get_file.py
- tests/test_lakefs_file.py
- tests/test_ls.py
- tests/test_put_file.py
This PR simplifies most tests by introducing a new fixture for the `LakeFSFileSystem` instance under test.
It also includes a docker-compose file for local development, which creates an ephemeral lakeFS quickstart instance with settings compatible to the defaults in the test fixtures.
> Simplify tests

- pyproject.toml
- src/lakefs_spec/__init__.py
This commit adds [setuptools-scm](https://pypi.org/project/setuptools-scm/) as a build dependency in order to dynamically determine the version number of the package from Git tags.
This prevents inconsistencies between the versions in the package and the repository, which have already bitten us before.
Since we are already managing release versions through Git tags (by virtue of GitHub releases), determining the package version in this way seems like the least error-prone approach to me.
A test release has already been made based on this PR:
- GitHub release: https://github.com/appliedAI-Initiative/lakefs-spec/releases/tag/v0.1.0rc5
- CI: https://github.com/appliedAI-Initiative/lakefs-spec/actions/runs/5973519124/job/16205942347
- PyPI: https://pypi.org/project/lakefs-spec/0.1.0rc5/ …
> Include setuptools-scm for version derivation from Git

- src/lakefs_spec/spec.py
The three additional arguments added here are:
- `verify_ssl`, to toggle whether or not to verify SSL certificates in HTTPS connections
- `ssl_ca_cert`, pointing to a PEM file for cert verification
- `proxy`, for giving a proxy server address.
Closes #31.
> Add more configuration arguments to lakeFS file system

- dev-deps.lock
- pyproject.toml
Since package publishing happens as part of CI exclusively, we don't need the `twine` dependency anymore.
Also, add the `keywords` metadata attribute to the package.
> Simplify deps

- src/lakefs_spec/commithook.py
- src/lakefs_spec/spec.py
Adds the repository, the branch, and the diff that is being committed as direct inputs to the commit hook.
Also updates the docstring for the `CommitHook` type. Arguments were renamed from `event` to `fs_event`, and `rpath` to `resource`, respectively, to avoid confusion.
Fixes #27.
> Improve flexibility of commithooks by adding more arguments

- tests/test_fs.py
When we passed in a lakeFS client, it was up in the air whether it would support instance caching properly. But now that we switched to the raw config, it is straightforward to check.
Adds a test checking the cache on the key (`_fs_token` attribute) and the cache size when initializing a new instance.
Fixes #3.
> Assert instance caching works by adding a test for it

- README.md
In the most recent commit hook interface changes, arguments were consolidated into a context object, and the event was turned into an enum.
Change the readme to reflect these changes.
> Update stale commit hook documentation

- README.md
- pyproject.toml
- src/lakefs_spec/spec.py
- tests/conftest.py
- tests/test_fs.py
Assumes the default location (`~/.lakectl.yaml`), and loads the config file if it exists and YAML is installed.
If YAML is not installed (this is not a hard requirement), it is possible to install it via `python -m pip install lakefs-spec[yaml]`. This extra is added specifically for `lakectl` configuration file support.
Also ignores missing imports from `pyyaml` under mypy.
Closes #43.
> Add lakectl config support

- .github/workflows/python.yaml
- hack/docker-compose.yml
- pyproject.toml
- requirements-dev.txt
- requirements.txt
Issue: #47
This PR unpins the `lakefs-client` dependency, updating it to the latest release `0.108.0`.
Due to a breaking API change, the sidecars for testing (docker-compose locally, GH actions) needed to be updated in lockstep.
> Unpin lakefs-client dependency

- .pre-commit-config.yaml
- requirements-dev.txt
- requirements.txt
`fsspec` 2023.9 includes our filesystem in the registry, and should always be kept up to date.
Some other tools also had new releases, notably `build` to stable 1.0.0.
> Bump multiple tools and dependencies to latest versions 

- tests/conftest.py
This way, a serious production config by a developer does not get forcefully overwritten when the `lakefs-spec` test suite is run.
> Fix temporary config fixture to back up lakectl config if existent

- src/lakefs_spec/spec.py
- tests/conftest.py
- tests/test_exists.py
- tests/test_rm.py
The fact that these were necessary and overdue is spelled out by a254a8a8c85c5507146e89ff5da0ac2400711231, which fixes a bug that prevented `fs.exists()` from ever working correctly in the first place.
Also changes the test configuration to pre-populate the test repository with sample data, which is useful all around for upcoming tests, such as pandas integration tests.
Closes #53.
> Add missing tests for `fs.exists()` and `fs.rm()`

- src/lakefs_spec/errors.py
- src/lakefs_spec/spec.py
Add an exception translation module, which provides a bit more flexibility than the context manager did.
For the future, we might want to think about allowing exception thunks (binding the error automatically) to give a more informative error depending on the type.
Also remove the unused `_rm` overload.
Closes #58.
> Better errors

- src/lakefs_spec/spec.py
- tests/test_lakefs_file.py
- tests/test_put_file.py
Also change tests to expect only Python-native errors.
Adds a test for unsupported file modes in `fs.open`.
> Wrap all API calls in `try-except`s

- .pre-commit-config.yaml
- README.md
- tests/conftest.py
- tests/test_get_file.py
- tests/test_put_file.py
Verifies through an API counter that prechecks save redundant operations by not requesting unnecessary API calls on a checksum match.
Also bumps `black` to version v23.9.1 via `pre-commit autoupdate`.
Closes #57.
> Add tests for file operations with prechecks

- src/lakefs_spec/spec.py
- tests/test_fs.py
We emit a warning if `pyyaml` is not installed and the user has a `.lakectl.yaml` config file available. Add a test to verify that warning.
> Add test for expected logs on missing YAML module

- hack/config/s3.json
- hack/lakefs-s3-local.yml
Helps to simulate lakeFS production deployments in local development.
The S3 emulator used is SeaweedFS, while for the database, the baked-in local postgres instance is kept.
> Add local S3 block storage adapter docker compose file

- README.md
- src/lakefs_spec/spec.py
- tests/test_checksum.py
- tests/test_get_file.py
- tests/test_put_file.py
This is what the keyword arguments were designed to do in the abstract file system base class, so it is only natural to do this. Also implicitly enables pre-signed URL support by passing `presign=True` to the `fs.ls` and `fs.get_file` methods.
Since the switch is scoped so narrowly to file transfers, take up `precheck` (formerly `precheck_files`) into the `fs.{get|put}_file` signatures as a keyword argument.
The client-side caching portion of the readme was rephrased to account for this new mode of operation.
> Pipe `**kwargs` to client API calls, make `precheck_files` a file op keyword argument

- src/lakefs_spec/spec.py
- tests/test_checksum.py
- tests/test_get_file.py
- tests/test_info.py
It is wasteful to always get the object list from `objects_api.list_object`, and might be slower for buckets/repos with lots of objects.
Hence, if we decide that the input to `fs.info` is a file (heuristic: input does NOT end on slash), we call the `objects_api.stat_object` endpoint instead.
Judging from an earlier debugging session, when requesting file info, this also saves some more API calls that would happen as a ripple effect from `fs.ls`.
> Call `objects_api.stat_object` endpoint in case of file in `fs.info`

- hack/lakefs-s3-local.yml
Unbreaks the `http://seaweedfs:` resolve failures in the lakeFS client by explicitly setting the IPv4 as S3 endpoint, and exposing port 9001 on the SeaweedFS container.
> Fix local S3 docker compose by switching to host networking

- src/lakefs_spec/spec.py
Otherwise, we throw away a full buffer because we do not upload until `final=True` (force-flush/file close).
Since our case is sufficiently different from the buffered standard implementation, we just override `flush` instead of tweaking the `_upload_chunk`.
Also, pipe file system blocksize to opened files - otherwise, the user has no control over the block size in a read (the write is unbuffered, anyway).
> Fix buffer deletes on upload

- src/lakefs_spec/hooks.py
- src/lakefs_spec/spec.py
Provides support for file read events (`mode == "rb"`) and changes the hook event from `PUT_FILE` to the newly created `FILEUPLOAD`.
Closes #83.
> Add file upload and download events and corresponding `LakeFSFile` hooks

- src/lakefs_spec/hooks.py
- src/lakefs_spec/spec.py
- tests/conftest.py
- tests/test_copy.py
A first implementation, directly calls into `objects_api.copy_object` after some input validation.
Only allows copies within a repo, since that limitation is imposed by the lakeFS client.
Does not check for a protocol, assumes string paths.
Adds a test as well.
Closes #79.
> Implement `LakeFSFilesystem.cp_file`

- src/lakefs_spec/spec.py
- tests/test_ls.py
Caches results of `fs.ls` calls in the class' `DirCache` instance.
As an added bonus, if a file is requested by `fs.ls` that has a cache entry for its parent, but is not yet found in the cache, this implementation will fetch those files and append them in the correct place in the existing cache entry. This "hot-reloading" of cache entries is a little more robust than just raising an exception and leaving the user to manually list the objects again.
Adds a test which verifies that the cache is hit on two identical `fs.ls` calls.
Does not assume cache size control or TTL, so this only checks a cache hit in the default configuration.
Closes #80.
> Implement directory listings caching for `ls`

- src/lakefs_spec/client_helpers.py
- tests/test_client_helpers.py
Add `client_helper` functions for convenience to use the lakeFS client. Add tests for these functions.
Closes https://github.com/appliedAI-Initiative/lakefs-spec/issues/82 by implementing
> Add new `client_helper` functions

- src/lakefs_spec/client_helpers.py
- tests/test_client_helpers.py
Very small PR adding the `rev-parse` client helper. 
Did not include tests as it would essentially be testing `lakeFS client` code.
> Add rev-parse client helper

- .github/workflows/python.yaml
- hack/docker-compose.yml
- hack/lakefs-s3-local.yml
- requirements-dev.txt
- requirements.txt
- src/lakefs_spec/__init__.py
- tests/conftest.py
Bumps core and dev dependencies, notably `fsspec`, `lakefs-client` and `urllib3`, the latter being a security advisory issued by dependabot on GitHub.
Bump docker compose files to use the latest stable lakeFS tag. This is currently v0.112.1, which carries some changes relevant to the Python userbase. Concretely, it seems that the `lakefs-client` package will eventually give way to the `lakefs-sdk` package.
> Update Python development dependencies and lakeFS docker image tags

- README.md
1) `df.to_csv` -> `df.to_parquet` (the given filename was actually lakes.parquet, so this was just a typo).
2) Add an example `lpath` to the `fs.scope` example (this was uncaught because the code cell did not carry the context from the above cell).
> Fix small README mistakes

- src/lakefs_spec/spec.py
- tests/test_blockstore.py
* Remove mutable dict default from `put_file`
* Move azure->az change to after the blockstore query to improve readability
* Move blockstore type query to the `presign=False` block to avoid the request when using presigned URLs.
> Small fixes re: blockstore puts

- CONTRIBUTING.md
- pyproject.toml
Since the filesystem was registered in `fsspec`'s known implementations, we do not need the entry point anymore.
> Remove setuptools/poetry entrypoint registration

- .github/workflows/python.yaml
- pyproject.toml
- requirements-dev.txt
- src/lakefs_spec/client_helpers.py
- src/lakefs_spec/config.py
- src/lakefs_spec/errors.py
- src/lakefs_spec/hooks.py
- src/lakefs_spec/spec.py
We want to at least support Python 3.9, so the following had to be changed:
1. `from __future__ import annotations` to enable `X | Y` union type annotations for pre-3.10 Python versions.
2. Set `StrEnum` as a str+Enum mixin in versions prior to 3.11. This is not strictly equivalent to Python 3.11's `StrEnum`, but for our uses it behaves exactly the same.
Fixes #103.
> Introduce future annotations and guard imports for Python 3.9 compat

- .github/workflows/python.yaml
- README.md
- demos/rain_prediction.ipynb
- demos/requirements.txt
- docs/use-cases.md
- hack/docker-compose.yml
- hack/lakefs-s3-local.yml
- pyproject.toml
- requirements-dev.txt
- requirements-docs.txt
- requirements.txt
- src/lakefs_spec/__init__.py
- src/lakefs_spec/client_helpers.py
- src/lakefs_spec/errors.py
- src/lakefs_spec/hooks.py
- src/lakefs_spec/spec.py
- src/lakefs_spec/util.py
- tests/conftest.py
- tests/test_blockstore.py
- tests/test_client_helpers.py
- tests/test_hooks.py
- tests/test_lakefs_file.py
- tests/test_put_file.py
- tests/test_rm.py
- tests/util.py
In preparation for the lakeFS v1 launch, change the package to depend on their newly launched `lakefs-sdk` to keep up to date with their upstream changes.
The import change is largely a name replacement only, with the exception of the model imports now happening from the `lakefs_sdk.models` subpackage.
> Change lakeFS package to `lakefs-sdk` in place of `lakefs-client`

- hack/README.md
Contains a few short explanatory sentences and instructions on the various deployments and when/how to use them, including cleanup for the S3 volume.
Also contains a mock credential file for running zero-config integration tests on blockstore puts (with `LakeFSFileSystem.put_file_to_blockstore`) in the case of S3 via SeaweedFS.
Let's see if dependabot starts screaming because of the credentials.
Closes #94.
> Add README on hack/ folder resources

- src/lakefs_spec/spec.py
Sets file sizes appropriately before uploads/downloads, and does relative updates for downloads.
Unfortunately, since the lakeFS server does not support multipart uploads, we do not get callback support for the `put_file` case; we just add a single 100%-chunk update after upload.
For the case of blockstore writes, we just pass the callback to the resulting file system's `put_file` implementation.
> Add fsspec callback support for `put_file` and `get_file`

- .pre-commit-config.yaml
- pyproject.toml
Requires some extra `pyproject.toml` configuration to behave the same, like specifying the line-length (100) and marking the `src` directory as source directory explicitly for understanding first party imports.
> Drop isort hook in favor of ruff plugin

- pyproject.toml
- tests/test_put_file.py
- tests/util.py
Includes removing a debug print statement that got checked in, and tightening the API counter instrumentation check to not include the `call_api_with_http_info` methods (they showed up in GitHub actions test logs).
> Minor test cleanups

- src/lakefs_spec/errors.py
- src/lakefs_spec/spec.py
These type hints are the strictest they can be without excessive errors.
This leads to a few relaxations, though:
* The `outfile` argument was reduced to `typing.Any`, since it is optionally assigned to a str or IO class, which is hard to capture and model correctly.
* Paths are currently limited to `str`s, since they are fed directly to the lakeFS URI regex parser.
Followup PRs could e.g. add support for `PathLike`s as {r,l}paths.
> Add type hints to lakeFS file and file system [ENG-123]

- .pre-commit-config.yaml
While it is considered experimental, it appears extremely capable, much much faster than black, and 99.99% compliant with black. Also, none of the listed intended departures from black style seem to apply to us.
Source on known deviations: https://docs.astral.sh/ruff/formatter/black/
> Switch out black for ruff format

- src/lakefs_spec/config.py
- tests/test_config.py
- tests/test_fs.py
Based on the class responsibility model, the `LakectlConfig` class should not assume that existence of the input file has already been checked.
However, in the file system case, this is necessary to gracefully decay into an empty config in case the default config does not exist, or cannot be read.
Fixes #126.
> Explicitly check for existence in `LakectlConfig.read()`

- .pre-commit-config.yaml
- src/lakefs_spec/spec.py
Otherwise, we do not have any automated formatting in CI anymore after the black removal.
Also fixes a format difference, inlining a larger comment.
> Add ruff-format hook

- src/lakefs_spec/client_helpers.py
- src/lakefs_spec/spec.py
- src/lakefs_spec/util.py
- tests/test_lakefs_file.py
- tests/test_transactions.py
Introduces a subclass of fsspec's builtin transactions called `LakeFSTransaction`, which in addition to its normal use has a number of predefined common versioning operations.
As the transaction is supposed to be used within the context manager block, the generator signature was changed to return the transaction instance, which is a departure from the fsspec instance.
When versioning operations are requested, they are forwarded to their respective client helper function along with their supplied arguments, and the stack of file objects and versioning ops is unwound in the context manager's exit method.
> Add lakeFS transactions

- pyproject.toml
- requirements.txt
- src/lakefs_spec/config.py
- tests/test_config.py
Since the PyYAML dependency is now mandatory, the check for it being installed is no longer necessary (as is the corresponding test).
Note: not updating the docs here, since this will happen in #129 and #142.
Closes issue #141
> Make `pyyaml` dependency mandatory

- src/lakefs_spec/spec.py
- tests/test_lakefs_file.py
This warning is intrusive and we have direct blockstore uploads available for users, so it can be removed. A note in the docs will be added in a follow-up.
> Remove file upload performance warning

- src/lakefs_spec/__init__.py
- src/lakefs_spec/client_helpers.py
- src/lakefs_spec/spec.py
- src/lakefs_spec/transaction.py
- tests/test_client_helpers.py
- tests/test_transactions.py
Similarly to `fsspec`, the transaction now lives in the `lakefs_spec.transaction` submodule.
Introduces the `Placeholder` generic type for a deferred value that is only available after transaction completion.
This is important for values that are not available immediately after execution of a transaction helper, such as a commit SHA, which has to be computed first by the backend, and this happens only on transaction completion.
To be able to still pass these values to other consumers in the transaction, the `ref` argument was changed to also take a `Placeholder` as an argument.
The placeholder is tracked by the transaction's file+op queue, and populated with the actual return value of the executed underlying client helper after the client helper operation completes.
In subsequent …
> Improve lakeFS transactions by using deque, placeholders for commit SHAs

- .github/actions/python-deps/action.yaml
- docs/mkdocs_customization/extra.css
- docs/tutorials/demo_data_science_project.ipynb
The previous iteration tried to give instructions for a hermetic virtual environment used via ipykernel, but never gave instructions on how to do so.
This change removes the recommendation to register the virtual environment as a hermetic kernel, and instead recommends to install all necessary dependencies into the single environment, including Jupyter Notebook itself.
Some minor style changes were made to the rest of the setup instructions, including capitalization of Docker everywhere and fixing some incorrect grammar.
> Reword Python environment installation guide

- src/lakefs_spec/client_helpers.py
- src/lakefs_spec/spec.py
- src/lakefs_spec/transaction.py
- tests/test_client_helpers.py
- tests/test_transactions.py
This ensures that usage can be made idempotent, which (for us) has the tangible advantage of allowing for faster docs development iterations.
The heuristic to detect a backend "exists" error is only the status code 409 for now, though we could also do a substring search on the reason. This however would incur a JSON parse.
Changes the tag creation API to return a `Ref` model object.
The `ensure_branch` was renamed to `create_branch` on account of the creation option `exist_ok` that was added.
Fixes #153.
> Add `exist_ok` flag to all resource-creating client helpers

- src/lakefs_spec/spec.py
- tests/test_ls.py
This PR improves the implementation of the `ls` operation:
- Returned items include their fully-qualified (repo + ref) path (#162)
- Dircache can be bypassed explicitly by passing the `refresh=True` parameter (#163)
- Dircache keys take repo + ref into account (otherwise the cache would yield false hits for objects with the same path on different branches) (#164)
> Improvements to `ls` implementation

- docs/guides/index.md
- docs/guides/integrations.md
- mkdocs.yml
This PR adds a page on the integration of lakefs-spec with third-party libraries to the user guide as `docs/guide/integrations.md`.
It includes explanations and code examples for:
- Pandas
- DuckDB
- Polars
- PyArrow
> [!NOTE]
> I wonder if the code examples should be included from external Python files, just as for the quickstart guide? This would allow us to run them as part of an integration test suite for the docs.
> Docs: Add third-party integrations user guide

- src/lakefs_spec/util.py
- tests/test_spec_utils.py
Since the scheme is a part of the URI, it should be allowed in the parsing regex. This is achieved by adding an optional positive lookahead capture group.
This has the benefit that the scheme, since we don't need it, does not appear in the regex match groups, so all other code can stay unchanged.
Adds a regression test for scheme parsing.
Fixes #159.
> Allow leading `lakefs://` scheme in input paths

- src/lakefs_spec/spec.py
- tests/test_info.py
- tests/test_ls.py
Previously, our heuristic for calling `objects_api.stat_object` was the resource terminating in a slash.
However, we put this into an `if-else` branch, meaning that `objects_api.list_objects` would never be called on a directory resource that was not slash-terminated. This leads to erroneous "not found" errors on existing directories.
The heuristic now changes to the strategy "call `stat_object` first, return if successful, otherwise call `list_objects`". This ensures that on an unsuccessful `stat_objects` call on a directory, the correct `list_objects` call follows directly afterwards.
Also adds a regression test for the behavior.
------
Repro on main (currently results in "404 not found" as mentioned above, requires a repo "lakefs-spec-tests" with sample data):
```python
from …
```
> Change `fs.info()` logic to recognize non-slash-terminated directories

- docs/guides/index.md
- docs/guides/transactions.md
Mentions the most important features of the lakeFS transaction, and states that they are the intended place for versioning operations.
> Add transaction usage document [ENG-150]

- CONTRIBUTING.md
- README.md
- docs/_styles/extra.css
- docs/guides/configuration.md
- docs/guides/filesystem-usage.md
- docs/guides/index.md
- docs/guides/integrations.md
- docs/index.md
- docs/quickstart.md
- docs/tutorials/index.md
- hack/README.md
- mkdocs.yml
- pyproject.toml
- requirements-docs.txt
- src/lakefs_spec/spec.py
This PR should bring the documentation to a release-ready state (except the tutorial notebook, which is in scope for #158).
Major changes:
- Consistent spelling: lakeFS-spec, lakeFS, and fsspec
- Removed use cases page from docs, needs major overhaul
- Removed reference to constructor args in configuration user guide, since they can cause consistency issues
> Documentation cleanup [ENG-198]

- docs/tutorials/demo_data_science_project.ipynb
Improves a few aspects of the tutorial:
* The weather API data is now saved to a temporary file, no more directories are created. The tempfiles are closed immediately after their last uses in the upload transactions.
* The separate `put` operation section was cut, because the showcase of a commit abort is unnecessary. Instead, the focus is shifted to the transactional upload of the data frames.
* Instead of shape comparisons, `pandas.DataFrame.equal` is used to establish equality of local vs. remote downloaded data. This actually caught a dtype mismatch between two datasets.
* Through style changes and regroups, a number of text passages were slimmed down or cut entirely.
> Change certain aspects of the data science tutorial notebook

- mkdocs.yml
- src/lakefs_spec/client_helpers.py
Add doc strings such that the `client_helpers` API are included in the documentation. 
This addresses https://github.com/aai-institute/lakefs-spec/issues/121
The question remains open whether we want doc-strings (and hence documentation) on all the members where I added them. Some might not be intended as public API. Refer to the linked issue for more details.
> Add doc-strings to the client_helpers

- docs/tutorials/demo_data_science_project.ipynb
- src/lakefs_spec/client_helpers.py
- src/lakefs_spec/transaction.py
- tests/test_client_helpers.py
- tests/util.py
Tags are immutable as per design from lakeFS (stated on lakeFS GUI tag site, no rename_tag API and their [docs](https://docs.lakefs.io/understand/model.html#tags)). The client helper returns the tag that is still pointing to the previously assigned commit. 
Therefore, 
Closes https://github.com/aai-institute/lakefs-spec/issues/165
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aai-institute/lakefs-spec/179)
> Adapt `create_tag` client helper to reflect tag immutability

- src/lakefs_spec/spec.py
Since we now account for a lakeFS URI scheme in the `parse` function (#169), we can drop the overload of `_strip_protocol` from the file system implementation.
Also removes its usages in our APIs, as is only logical if the `parse` function does the same job.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aai-institute/lakefs-spec/174)
> Remove `_strip_protocol` overload and usages

- src/lakefs_spec/spec.py
- tests/test_client_helpers.py
- tests/test_put_file.py
This has realistically been superseded by the new `LakeFSTransaction.create_branch` functionality, since that provides the same API, in an easier interface, with the same context manager error handling capabilities.
However, the class-wide `create_branch_ok` and `source_branch` attributes are still useful to implicitly create branches without having to start transactions with a verbose leading `tx.create_branch`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aai-institute/lakefs-spec/175)
> Remove `LakeFSFileSystem.scope` context manager

- src/lakefs_spec/client_helpers.py
- src/lakefs_spec/spec.py
- src/lakefs_spec/util.py
- tests/test_client_helpers.py
This is basically the lakeFS SDK example with some typing to improve the expected inputs and outputs.
I'm pretty sure the generic typing does not work, since mypy does not make the connection from a pydantic response model (say, `RefList`) to the result type (in this case, `list[Ref]`).
My idea was a "C++ template specialization" kind of approach, forwarding `RefList = PaginatedApiResponse[Ref]`, but it seems like that's not directly possible in the current typing.
This also likely needs some logic to accommodate Python 3.9 with the `ParamSpec` usage and so on.
Closes #178.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aai-institute/lakefs-spec/180)
> Add depagination helper

- src/lakefs_spec/spec.py
Annotates all overloaded methods, both public and private, on the `LakeFSFileSystem` and `LakeFSFile` classes.
Some hints about input values (e.g. `rpath`s having to be fully qualified lakeFS URIs) were duplicated across all APIs, since a user might use only a subset of APIs.
Also forwards the `LakeFSFile`'s keyword arguments supplied on construction to the respective `objects_api.{get,put}_object` calls.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aai-institute/lakefs-spec/181)
> Create API docstrings for the `LakeFSFileSystem` and `LakeFSFile`

- src/lakefs_spec/client_helpers.py
- src/lakefs_spec/config.py
- src/lakefs_spec/errors.py
- src/lakefs_spec/transaction.py
- src/lakefs_spec/util.py
Contains API and module docstrings for the `lakefs_spec.config`, `lakefs_spec.errors`, `lakefs_spec.transaction`, and `lakefs_spec.util` modules.
The versioning method docs on the `LakeFSTransaction` were mostly copied over from the respective client helpers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aai-institute/lakefs-spec/184)
> Add API docs for all remaining smaller modules

- .github/workflows/python.yaml
In order to gauge the effectiveness of our test suite, we should not
only measure coverage on our own code, but rather on the abstract
base classes for the file system and file implementations as well.
This commit adds the necessary parameters to the pytest invocation
in CI, which then ends up in the CodeCov reports.
> Record test coverage on fsspec package [ENG-196]

- src/lakefs_spec/errors.py
- src/lakefs_spec/spec.py
- tests/test_errors.py
- tests/test_get_file.py
- tests/test_put_file.py
Prepares the `status`, `reason`, and `filename` arguments unconditionally for each observed API error.
This way, users who see translated errors actually know what the filename involved is instead of just getting the (less than ideal) lakeFS API reason.
One particular behavior is that of `fs.ls()` in case the branch/ref is not found: Here, unlike in the repository case, the branch is not part of the error message, which means just a generic "file not found" error.
We use OS Errnos for more exotic statuscodes, and HTTP codes for 401, 403 and 404 errors.
> Modify error translator to raise more informative errors

- docs/guides/transactions.md
The transaction user guide included code examples that mistakenly referred to `tx.put_file`, which does not exist.
> Docs: Fix typos in tx user guide

- README.md
- docs/index.md
- requirements-dev.txt
- requirements-docs.txt
This PR adds a call to action to early adopters to the documentation landing page and (repository) README.
https://github.com/aai-institute/lakefs-spec/security/dependabot/8 is addressed by updating the documentation dependencies.
> Docs: Add call to action for early adopters to README and landing page [ENG-186]

- src/lakefs_spec/client_helpers.py
- src/lakefs_spec/spec.py
- tests/test_client_helpers.py
- tests/test_ls.py
This PR combines various fixes to the handling of the directory listing cache and `ls` behavior in general:
The `ls` method in its previous implementation would always return items in subdirectories recursively, which is not an intuitive behavior.
This PR introduces an optional `recursive` kwarg, which is set to `False` by default.
The `ls` command was not updating the dircache correctly, which could lead to incorrect results when listing the same directory multiple times.
In particular, the implementation would always add all results from the API call to the dircache for the directory, regardless of whether the results were already in the cache entry (essentially doubling the cache entry for each subsequent call).
This behavior would only be triggered by passing `refresh=True`, which …
> `ls`: Make non-recursive by default, correctly update dircache

- .github/workflows/python.yaml
- .github/workflows/release.yaml
- hack/docker-compose.yml
- hack/lakefs-s3-local.yml
- pyproject.toml
- requirements-dev.txt
- requirements-docs.txt
- src/lakefs_spec/spec.py
- tests/smoke_tests/test_abstractfile.py
- tests/smoke_tests/test_abstractfilesystem.py
- tests/test_internals.py
- tests/test_spec_utils.py
This PR adds a variety of smoke tests that aim to cover the default functionality provided by the abstract base classes from `fsspec`, namely `AbstractFileSystem` and `AbstractBufferedFile`.
In order to avoid the problem discovered by one of the tests and reported upstream ( https://github.com/treeverse/lakeFS/issues/7127), the version of lakeFS dependencies has been bumped to v1.3.1 in the CI and dev environments.
> [!NOTE]
> These tests are not meant to provide complete coverage of the base implementations, since these are tested as part of `fsspec` already.
> Rather, they aim to uncover any potential issues that arise from the mix of overwritten and default implementations and their interactions (e.g., quite a few implementations in the ABC rely on the return value from `ls`, which is …
> Improve test coverage on lakefs abstract base classes

- .pre-commit-config.yaml
- pyproject.toml
- requirements-dev.txt
- src/lakefs_spec/client_helpers.py
- src/lakefs_spec/config.py
- src/lakefs_spec/errors.py
- src/lakefs_spec/spec.py
- src/lakefs_spec/transaction.py
- src/lakefs_spec/util.py
This PR adds `pydoclint` as a dev dependency and pre-commit hook.
All non-confirming docstrings in the source code have been updated to pass the check.
> Validate with docstrings with `pydoclint`

- src/lakefs_spec/spec.py
Previously, the file was closed again on deletion, which is bad practice if an exception occurred in write mode, since any exception on write will immediately reappear in the exit routine.
This has potential to disturb Python exit cleanup, so we just unset the closing attempt in `__del__`. Any users wanting to upload a file implicitly have to use a context manager (which is preferred, anyway), otherwise, they have to call `file.close()` themselves.
Fixes #218.
> Overload `LakeFSFile.__del__` to pass statement

- src/lakefs_spec/spec.py
Specializes the return type as `list[dict[str, Any]]` for `detail=True`, and `list[str]` for `detail=False`.
Unfortunately, since the base class has a keyword argument default, the `Literal[False]` overload is still marked by the IDE.
Furthermore, the typing is changed to `list[str] | list[dict[str, Any]]`, since that is only equivalent to `list[str | dict[str, Any]]` in case of a homogeneous list. This is our case, but the former list union type explicitly conveys type homogeneity.
> Add overloads for `LakeFSFileSystem.ls()`

- docs/tutorials/demo_data_science_project.py
- pyproject.toml
This PR adds a simple client-side caching function to the tutorial notebook, whichs prevents the same file from being downloaded multiple times.
This avoids hitting the API rate limit when working on the notebook locally.
Closes issue #192
> Docs: Client-side caching for Open-Meteo API in tutorial notebook

- mkdocs.yml
Since `LakeFSFile.__del__` was overloaded, it appeared in the docs, as mkdocstrings only removes single-underscore methods from the rendered documentation.
`__init__` methods are excluded with a different flag already, so to fix, just extend the filter regex to double-leading-underscore methods.
> Remove dunder methods from API docs

- src/lakefs_spec/spec.py
- tests/test_ls.py
The previous implementation of `ls` would only update the dircache for a single directory, based on the order of info entries returned from the API.
The new implementation correctly adds all directory entries to the dircache, and makes sure that the responses returned from the cache correctly honor the `recursive` flag.
Closes #200
> Correctly handle dircache for recursive `ls` calls

- pyproject.toml
- requirements-dev.txt
- requirements-docs.txt
- src/lakefs_spec/transaction.py
- tests/test_transactions.py
Using `wrapt` to refactor the `Placeholder` class with `wrapt.ObjectProxy` as a transparent proxy. 
Remove the need for `unwrap` via overriding of `__getattr__`.
Delete `unwrap_placeholders` utility function.
Make the `available` method an attribute as it needs no computation input.
Update maintainer e-mails to institute addresses.
Closes https://github.com/aai-institute/lakefs-spec/issues/207
> Simplify transaction `Placeholder` class

- docs/guides/transactions.md
- mkdocs.yml
The newest PR has made the use of `Placeholder.unwrap()` obsolete, so the value can be reused as is, with the same semantics.
Changes the paragraph and code example accordingly to reflect this fact.
> Fix transaction doc on `Placeholder` values

- .github/workflows/release.yaml
The `github.ref_name` context property appears to no longer be set when making a release through the UI.
This PR applies a workaround, using the `github.event.release.tag_name` property instead.
See actions/runner#2788 for details.
Issue: #227
> Correctly set docs version number for release workflow

- tests/conftest.py
- tests/smoke_tests/test_abstractfile.py
- tests/smoke_tests/test_abstractfilesystem.py
1) Remove `ensurerepo`, and just ensure the repository directly in `repository`.
2) Rename `test_info` to `test_fileinfo` to more directly convey that it is the file's info attribute that is being tested. 
3) Remove the temporary directory from `test_get_file` to prefer the `tmp_path` fixture, which has automatic cleanup.
> Several small test improvements

- src/lakefs_spec/spec.py
- tests/test_rm.py
This happens by a) setting a delimiter in the object listing depending on the value of `recursive` ("/" means directory-local listings), and b) by filtering all results that have a sufficient number of slashes in their file names if `maxdepth` is an integer.
Checks that a subdirectory is not deleted by `fs.rm(..., recursive=False)`.
> Fix `fs.rm()` for the recursive case

- tests/test_exists.py
- tests/test_info.py
- tests/test_ls.py
Informative file system APIs like `fs.info()`, `fs.ls()` and `fs.exists()` should work on branches as well as commits, since they carry a meaning for commits as well, as opposed to state-changing APIs like `fs.rm()`.
For this reason, check that these APIs perform the same as for a branch input by checking them against a branch and the `branch@HEAD` commit subsequently, comparing the results. Result equality is expected.
Closes #242.
> Add test coverage for commits to repo information tests

- pyproject.toml
- src/lakefs_spec/transaction.py
- tests/test_transactions.py
As a consequence of my complaints upstream, a new `ReferenceType` was added, which is the union of `str` and everything that marks a reference in lakefs Python code (branches, tags, commits). We now use this everywhere, as it saves space in the interfaces.
Also, since the placeholder is ducktyped to be a ReferenceType always, and passes type checks at runtime (isinstance only), the typing could be relaxed to work with the native reference type only.
Part of #233.
> Remove Placeholder from interface typing, use new ReferenceType hint

- docs/tutorials/demo_data_science_project.py
- src/lakefs_spec/spec.py
From a newly raised issue in lakeFS, it came out that you can actually construct refs from git-like revision selectors, among which is also `$BRANCH~N`, i.e. branch ancestor syntax.
This makes the code much easier and requires only a single API call.
> Simplify revision parsing in the tutorial notebook

- src/lakefs_spec/spec.py
- tests/test_lakefs_file.py
This is sensible because a) the builtin `fs.open()` was giving wrong type hints of `AbstractBufferedFile`s, which we no longer use, and b) the new lakeFS APIs allow native handling of non-bytemode open(), which the base `fs.open()` needs a TextIOWrapper for.
No new tests, since all file-system APIs are already being tested. What is missing are integration tests to pandas, polars, etc., since those all rely on `fs.open()`.
> Replace `fs._open()` with proper `fs.open()` implementation

- docs/guides/transactions.md
- src/lakefs_spec/transaction.py
Closes https://github.com/aai-institute/MLOps-Engineering/issues/29
> (docs): Add lakeFS-spec and lakeFS-SDK transaction differences

- .pre-commit-config.yaml
- README.md
- docs/_code/duckdb_example.py
- docs/_code/pandas_example.py
- docs/_code/polars_example.py
- docs/_code/pyarrow_example.py
- docs/_code/quickstart.py
- docs/guides/transactions.md
- docs/tutorials/demo_data_science_project.py
- pyproject.toml
- requirements-dev.txt
- requirements-docs.txt
- src/lakefs_spec/spec.py
- src/lakefs_spec/transaction.py
- tests/test_put_file.py
- tests/test_rm.py
- tests/test_transactions.py
This is a breaking change, as it requires users to give arguments to the return object of `LakeFSFileSystem.transaction`.
Changes the `LakeFSTransaction` class to become a repository+branch-scoped ephemeral branch.
File uploads, removals, and commits happen on that ephemeral branch. After transaction exit, the created branch is optionally merged back into the base branch.
The base branch (from which we branch off in the transaction) must exist before start of the transaction.
Some transaction APIs (merge, revert, tag) can also work on branches other than the transaction's ephemeral branch - this behavior might not be well-defined, and is up for debate on removal.
Similarly, on puts and deletes, one currently has to specify the transaction branch directly via the `LakeFSTransaction.branch` …
> Introduce new transaction model based on ephemeral branches

- src/lakefs_spec/transaction.py
- tests/test_transactions.py
> Log a warning for uncommitted changes on transaction exit

- docs/_theme_overrides/partials/header.html
When scrolling down on a documentation page, the page header will change from showing the project title (i.e. lakeFS-spec) to showing the current page title.
From that point on there is no more visual indication that you are viewing the lakeFS-spec documentation.
This change will prepend the project title to the page title.
> Always show the project name in the header

- .pre-commit-config.yaml
- docs/_code/polars_example.py
- docs/guides/integrations.md
After a refactoring of the transactions feature, the code examples themselves were modied, but not the page that highlights some lines in them.
This PR updates those code blocks to make them consistent with the actual example code.
Additionally, it pins the Python version used for pre-commit hooks to 3.11, to prevent problems on systems with Python 3.12 (which would be used to lock dependencies using `pip-compile`, which includes the Python version number in a comment in the generated dependency lock file).
Closes #267
> Docs: Fix code highlighting in third-party libraries integration guide

- .github/actions/python-deps/action.yaml
- .github/workflows/python.yaml
- .github/workflows/release.yaml
The `upload_artifact`/`download_artifact` actions were using the outdated NodeJS v16 runtime in version v3, which we depended on.
This commit bumps them to the latest version, addressing the [deprecation warnings](https://github.com/aai-institute/lakefs-spec/actions/runs/8092428162) raised by the release workflow.
Also, the lakeFS sidecar container version needed for the docs builds has been made consistent with the PR workflow (which was using the latest Docker image by default).
See: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-
node-20/
Note to reviewer: Sorry for the whitespace re-formatting - we should probably adopt common YAML formatting settings going forward ;)
> Update outdated CI actions

- .pre-commit-config.yaml
- src/lakefs_spec/spec.py
- src/lakefs_spec/util.py
This updates ruff to v0.3.1, which brings a few changes to the default code style.
> Update pre-commit hooks

- README.md
Replaced the old link(s) within the README.md that caused a 404, with the correct user guide and tutorial link.
> Fixed broken URL in README.md

- docs/_scripts/gen_api_ref_pages.py
- pyproject.toml
- requirements-docs.txt
- src/lakefs_spec/spec.py
This adds functionality to `gen_api_ref_pages.py` to extract the module docstrings for root-level modules in the package, and adds links to them to the index page of the API reference.
See also previous PR: #272
> Docs: Link to root-level modules in API docs

- README.md
- docs/_code/hf_datasets_example.py
- docs/guides/integrations.md
- docs/index.md
Similar to the [lakeFS PR](https://github.com/treeverse/lakeFS/pull/7613), this PR adds an example of how to interact with lakeFS repositories from the HF Datasets library.
It also adds a mention of the library in the repository README and docs landing page.
> Docs: Demonstrate integration of Hugging Face Datasets

- .pre-commit-config.yaml
- requirements-docs.txt
This addresses a Dependabot alert about a vulnerability in black: https://github.com/aai-institute/lakefs-spec/security/dependabot/15
Also bumps pre-commit hooks:
- mypy 1.8.0 -> 1.9.0
- ruff 0.3.1 -> 0.3.5
- bandit 1.7.7 -> 1.7.8
> Bump linter dependencies

- pyproject.toml
- src/lakefs_spec/errors.py
- src/lakefs_spec/spec.py
- src/lakefs_spec/transaction.py
- tests/test_put_file.py
This means that the polymorphic filesystem facility, which was upstreamed to fsspec and first appeared in that release, can go away.
----------------
Contains the error handling fix from #278 as a cherrypick.
> Bump minimum fsspec version to 2023.12.0

- src/lakefs_spec/spec.py
- src/lakefs_spec/util.py
lakeFS supports a maximum of 1000 objects per `delete_objects()` invocation, since that calls the object deletion API under the hood. This limitation is not without precedent, and exists also e.g. on AWS S3.
Hence, we batch delete objects on the client side, dispatching multiple API calls in the cases where the deleted objects list contains more than a thousand objects.
The threshold number of objects is currently hardcoded to 1000, since that is the limitation of the lakeFS server.
Fixes #284.
> Batch objects in `Branch.delete_objects` calls

- .github/workflows/python.yaml
- CONTRIBUTING.md
- codecov.yml
- docs/quickstart.md
- hack/README.md
- hack/compose.yml
- hack/lakefs-s3-local.yml
- src/lakefs_spec/spec.py
- src/lakefs_spec/util.py
- tests/test_exists.py
- tests/test_util.py
This PR implements `fs.exists()` on the root of a repository.
Semantically, checking the existence of a repo root equals checking if the specified ref (commit ID/branch name) exists in the repository.
Additionally, it fixes an inconsistency between the `batched` utility function between Python <3.12 and later versions and expands test coverage in CI to all supported Python versions.
Fixes issue #291
> Support `fs.exists()` on repo root

- .github/workflows/python.yaml
This PR improves test coverage in CI by running all tests against the matrix composed by:
- All supported Python versions: 3.10, 3.11, 3.12
- Runner OS: `ubuntu-latest`
- Earliest and latest supported `lakefs` and `fsspec` combos (in tandem to reduce combinatorial explosion, so only one case for either earliest or latest fsspec+lakefs version)
> CI: Run tests against oldest and latest supported versions of lakefs and fsspec

- pyproject.toml
- tests/test_rm.py
- uv.lock
By employing simple `asyncio` thread parallelism, the execution of the `test_rm_with_1k_objects_or_more` test is sped up from ~60s to around ~5s.
Unfortunately, this requires the `pytest-asyncio` plugin, but IMO the overall speedup is worth the extra dev dependency.
> Tests: Speed up `test_rm_with_1k_objects_or_more`

- .github/workflows/python.yaml
- .pre-commit-config.yaml
- uv.lock
Now that it's released, we should test it.
--------------
This will not pass until pyarrow (and possibly others) release Python 3.13 wheels. Until then, we could look at marking integration tests as xfail for 3.13, but not sure if that's worth the effort.
> Add Python 3.13 to test matrix

- src/lakefs_spec/util.py
- tests/test_spec_utils.py
This loses a bit of performance, but allows us to improve the error message to the user by attaching information about which part of the URI was invalid.
Since we consider the regexes an implementation detail, we do not return them in the error message.
Changes the failure test to include the expected invalid parts to harden the test case.
Part of #299.
> Improve error message in `util.parse()` by incrementally using regexes

- src/lakefs_spec/spec.py
- tests/regression/test_gh_297.py
- tests/test_ls.py
This PR fixes the `ls` implementation to exclude partial (prefix-only) matches when listing objects in a repository.
The previous behavior would incorrectly include files with names that are a prefix of the path passed to `ls`, e.g., a file named `foo/bar_1` would be included when listing `foo/bar` (a directory).
The root cause is that the `GET /repositories/{repository}/refs/{ref}/objects/ls` lakeFS API call returns objects based on their prefix, not full name matches, so we have to perform additional filtering in our `ls` method.
A regression test has been added based on the issue description.
Issue: #297
> Handle partial name matches in `ls` method

- src/lakefs_spec/util.py
- tests/regression/test_gh_299.py
- tests/test_spec_utils.py
Adds dot ("."), caret ("^"), and tilde ("~") to the ref identifier regex portion, since they are allowed in ref expressions in lakeFS.
New test cases for each of these scenarios were added to the existing parsing test.
------------
~Also contains a round of `pre-commit autoupdate` that I checked in by mistake apparently.~
Ancestor statements were ~not yet~ verified to work on e.g. a lakeFS quickstart sidecar container, I plan to do that early tomorrow. (But allowing them probably won't hurt, simply because lakeFS mentions them as part of their ref spec.)
> Support a wider range of ref expressions

- .github/actions/python-deps/action.yaml
- .github/workflows/release.yaml
Otherwise, setuptools_scm gets confused and creates a dev version even on a published tag.
> Run `uv sync --frozen` to not update the lock file in CI

- .github/workflows/release.yaml
A generated attestation in the upload job can only be used for a single upload, and is not cleared between uploads - hence, the PyPI release workflow reuses the attestation of TestPyPI, and gets rejected.
For now, remove the TestPyPI upload, so that we don't run into the stale attestation problem.
> Remove TestPyPI upload due to attestation failure

- README.md
- docs/quickstart.md
Syntax is literally the same, but we actually use uv, and poetry usage seems to dwindle within the Python ecosystem.
> Change poetry mentions to uv

- .github/actions/python-deps/action.yaml
- .github/workflows/python.yaml
- CONTRIBUTING.md
- pyproject.toml
- uv.lock
These are now supported by uv, and since they are dev-only (lakefs-spec does not contain any user-facing extra functionality), we can move them to PEP735 dependency groups instead.
> Use PEP735 dependency groups instead of extras

- CONTRIBUTING.md
Follow-up of the switch to dependency groups in #308.
> Tweak dependency addition guide with `uv add`, dependency groups

- .github/actions/python-deps/action.yaml
- .github/workflows/python.yaml
v5 of `setup-uv` adds caching and a default venv, so things should be a bit faster on repeated runs.
Since `python-version` allows bootstrapping a Python version directly on action setup, we do that instead.
> Update `setup-uv` action to v5, tweak install and setup

- src/lakefs_spec/transaction.py
lakeFS [v1.48.0](https://github.com/treeverse/lakeFS/releases/tag/v1.48.0) added squash-merging, which, as the name suggests, merges a source branch into a target branch by squashing the additional history into a single commit (which is also actually the merge commit in lakeFS).
The interesting thing is that it enables squashing _by default_, which changes the user-facing behavior of our (merge-based) transactions, and also all other merges done via `tx.merge()`.
This broke some of our transaction tests, which try to assert correct behavior by counting commits since branch creation, and verify by commit message.
This commit fixes the tests by introducing a new `squash` flag to the transaction class, which controls squash-merging of the transaction branch and any other branches/refs merged …
> Add squash-merging flag to transactions

- .pre-commit-config.yaml
- uv.lock
Contains a lockfile update from running `uv lock -U` on the current lockfile.
This means deps are upgraded, and the lakefs-spec version is replaced by an editable install.
> chore: Use uv v0.5.20 with dynamic versioning fixes

- src/lakefs_spec/util.py
- tests/regression/test_gh_314.py
- tests/test_util.py
The URI validation logic was too strict in some cases, causing valid lakeFS ref expressions with relative (`~N`, `^N`) or HEAD (`@`) suffixes to be rejected.
This PR refactors the relevant regexp to accept these URIs and also makes the relative ref expression parsing more explicit in the regex.
Issue: #314
> Make lakeFS URI validation more lenient

- .github/workflows/python.yaml
- .pre-commit-config.yaml
- hack/compose.yml
- src/lakefs_spec/spec.py
- src/lakefs_spec/types.py
- src/lakefs_spec/util.py
- tests/regression/test_gh_319.py
- tests/test_checksum.py
- tests/test_info.py
This PR adds custom object metadata to the result of `fs.info()`.
Additionally, it adds stricter type hints on the return value of `fs.info()` for better type checking and IDE support.
See issue #319.
> Return custom object metadata from `fs.info()` 

- docs/tutorials/demo_data_science_project.py
Currently, this prevents local rebuilds of documentation, since the lakeFS server will return a failure on attempting to recreate the repository if it already exists.
> docs(demo): Set `exist_ok=True` in demo repository creation

- docs/guides/filesystem-usage.md
- src/lakefs_spec/spec.py
- src/lakefs_spec/types.py
- tests/test_fs.py
Then, they are supposed to be forwarded to the raw lakeFS client API calls. This makes it possible to pass relevant parameters like timeouts to the actual API calls that are happening under the hood.
---------------------
Works towards #329. The PR on the lakeFS side, which is https://github.com/treeverse/lakeFS/pull/9509, provides kwargs support to many, but I think not all object functionality.
Needs testing against a new `lakefs` Python package release, and better docstrings.
> feat(fs): Pass kwargs to SDK object wrapper calls
